
const storeData = [
    {
      id: '1',
      storeName: '三田',
      address: '東京都港区三田',
      closedDays: '日曜日・祝日',
      imageUrl: 'https://example.com/mita.jpg',
    },
    {
      id: '2',
      storeName: '目黒',
      address: '東京都目黒区目黒',
      closedDays: '水曜日',
      imageUrl: 'https://example.com/meguro.jpg',
    },
    {
      id: '3',
      storeName: '八王子野猿街道',
      address: '東京都八王子市堀之内',
      closedDays: '月曜日',
      imageUrl: 'https://example.com/yaen.jpg',
    },
    {
      id: '4',
      storeName: '池袋東口',
      address: '東京都豊島区南池袋',
      closedDays: '月曜日',
      imageUrl: 'https://example.com/ikebukuro.jpg',
    },
    {
      id: '5',
      storeName: '亀戸',
      address: '東京都江東区亀戸',
      closedDays: '水曜日',
      imageUrl: 'https://example.com/kameido.jpg',
    },
    {
      id: '6',
      storeName: '京急川崎',
      address: '神奈川県川崎市川崎区本町',
      closedDays: '日曜日・祝日',
      imageUrl: 'https://example.com/keikyu_kawasaki.jpg',
    },
    {
      id: '7',
      storeName: '府中',
      address: '東京都府中市宮西町',
      closedDays: '水曜日',
      imageUrl: 'https://example.com/fuchu.jpg',
    },
    {
      id: '8',
      storeName: '松戸駅前',
      address: '千葉県松戸市本町',
      closedDays: '火曜日',
      imageUrl: 'https://example.com/matsudo.jpg',
    },
    {
      id: '9',
      storeName: 'めじろ台',
      address: '東京都八王子市椚田町',
      closedDays: '木曜日',
      imageUrl: 'https://example.com/mejirodai.jpg',
    },
    {
      id: '10',
      storeName: '荻窪',
      address: '東京都杉並区荻窪',
      closedDays: '日曜日',
      imageUrl: 'https://example.com/ogikubo.jpg',
    },
    {
      id: '11',
      storeName: '上野毛',
      address: '東京都世田谷区上野毛',
      closedDays: '日曜日・祝日',
      imageUrl: 'https://example.com/kaminoge.jpg',
    },
    {
      id: '12',
      storeName: '京成大久保',
      address: '千葉県習志野市大久保',
      closedDays: '水曜日',
      imageUrl: 'https://example.com/keisei_ookubo.jpg',
    },
    {
      id: '13',
      storeName: '環七一之江',
      address: '東京都江戸川区春江町',
      closedDays: '月曜日',
      imageUrl: 'https://example.com/ichinoe.jpg',
    },
    {
      id: '14',
      storeName: '相模大野',
      address: '神奈川県相模原市南区相模大野',
      closedDays: '日曜日',
      imageUrl: 'https://example.com/sagamiono.jpg',
    },
    {
      id: '15',
      storeName: '横浜関内',
      address: '神奈川県横浜市中区長者町',
      closedDays: '水曜日',
      imageUrl: 'https://example.com/kannai.jpg',
    },
    {
      id: '16',
      storeName: '神田神保店',
      address: '東京都千代田区神田神保町',
      closedDays: '日曜日・祝日',
      imageUrl: 'https://example.com/jimbocho.jpg',
    },
    {
      id: '17',
      storeName: '小店',
      address: '東京都江戸川区西小岩',
      closedDays: '月曜日',
      imageUrl: 'https://example.com/koiwa.jpg',
    },
    {
      id: '18',
      storeName: 'ひばりヶ丘駅前',
      address: '東京都西東京市谷戸町',
      closedDays: '火曜日',
      imageUrl: 'https://example.com/hibarigaoka.jpg',
    },
    {
      id: '19',
      storeName: '桜台駅前',
      address: '東京都練馬区桜台',
      closedDays: '水曜日',
      imageUrl: 'https://example.com/sakuradai.jpg',
    },
    {
      id: '20',
      storeName: '栃木街道',
      address: '栃木県下都賀郡壬生町壬生甲',
      closedDays: '月曜日',
      imageUrl: 'https://example.com/tochigi.jpg',
    },
    {
      id: '21',
      storeName: '立川',
      address: '東京都立川市柴崎町',
      closedDays: '月曜日',
      imageUrl: 'https://example.com/tochigi.jpg',
    }
]

export default storeData;