
const storeData = [
    {
      id: '1',
      storeName: '三田本店',
      address: '東京都港区三田2-16-4',
      closedDays: '日曜日・祝日',
      imageUrl: 'https://example.com/mita.jpg',
    },
    {
      id: '2',
      storeName: '目黒店',
      address: '東京都目黒区目黒3-7-2',
      closedDays: '水曜日',
      imageUrl: 'https://example.com/meguro.jpg',
    },
    {
      id: '3',
      storeName: '八王子野猿街道店2',
      address: '東京都八王子市堀之内2-13-16',
      closedDays: '月曜日',
      imageUrl: 'https://example.com/yaen.jpg',
    },
    {
      id: '4',
      storeName: '池袋東口店',
      address: '東京都豊島区南池袋2-27-17',
      closedDays: '月曜日',
      imageUrl: 'https://example.com/ikebukuro.jpg',
    },
    {
      id: '5',
      storeName: '亀戸店',
      address: '東京都江東区亀戸4-35-17',
      closedDays: '水曜日',
      imageUrl: 'https://example.com/kameido.jpg',
    },
    {
      id: '6',
      storeName: '京急川崎店',
      address: '神奈川県川崎市川崎区本町2-10',
      closedDays: '日曜日・祝日',
      imageUrl: 'https://example.com/keikyu_kawasaki.jpg',
    },
    {
      id: '7',
      storeName: '府中店',
      address: '東京都府中市宮西町1-15-5',
      closedDays: '水曜日',
      imageUrl: 'https://example.com/fuchu.jpg',
    },
    {
      id: '8',
      storeName: '松戸駅前店',
      address: '千葉県松戸市本町17-21',
      closedDays: '火曜日',
      imageUrl: 'https://example.com/matsudo.jpg',
    },
    {
      id: '9',
      storeName: 'めじろ台店',
      address: '東京都八王子市椚田町513-3',
      closedDays: '木曜日',
      imageUrl: 'https://example.com/mejirodai.jpg',
    },
    {
      id: '10',
      storeName: '荻窪店',
      address: '東京都杉並区荻窪4-33-1',
      closedDays: '日曜日',
      imageUrl: 'https://example.com/ogikubo.jpg',
    },
    {
      id: '11',
      storeName: '上野毛店',
      address: '東京都世田谷区上野毛1-26-16',
      closedDays: '日曜日・祝日',
      imageUrl: 'https://example.com/kaminoge.jpg',
    },
    {
      id: '12',
      storeName: '京成大久保店',
      address: '千葉県習志野市大久保1-5-8',
      closedDays: '水曜日',
      imageUrl: 'https://example.com/keisei_ookubo.jpg',
    },
    {
      id: '13',
      storeName: '環七一之江店',
      address: '東京都江戸川区春江町4-6-3',
      closedDays: '月曜日',
      imageUrl: 'https://example.com/ichinoe.jpg',
    },
    {
      id: '14',
      storeName: '相模大野店',
      address: '神奈川県相模原市南区相模大野6-14-9',
      closedDays: '日曜日',
      imageUrl: 'https://example.com/sagamiono.jpg',
    },
    {
      id: '15',
      storeName: '横浜関内店',
      address: '神奈川県横浜市中区長者町6-94',
      closedDays: '水曜日',
      imageUrl: 'https://example.com/kannai.jpg',
    },
    {
      id: '16',
      storeName: '神田神保町店',
      address: '東京都千代田区神田神保町1-21-4',
      closedDays: '日曜日・祝日',
      imageUrl: 'https://example.com/jimbocho.jpg',
    },
    {
      id: '17',
      storeName: '小岩店',
      address: '東京都江戸川区西小岩3-31-13',
      closedDays: '月曜日',
      imageUrl: 'https://example.com/koiwa.jpg',
    },
    {
      id: '18',
      storeName: 'ひばりヶ丘駅前店',
      address: '東京都西東京市谷戸町3-27-24',
      closedDays: '火曜日',
      imageUrl: 'https://example.com/hibarigaoka.jpg',
    },
    {
      id: '19',
      storeName: '桜台駅前店',
      address: '東京都練馬区桜台1-5-1',
      closedDays: '水曜日',
      imageUrl: 'https://example.com/sakuradai.jpg',
    },
    {
      id: '20',
      storeName: '栃木街道店',
      address: '栃木県下都賀郡壬生町壬生甲3705-1',
      closedDays: '月曜日',
      imageUrl: 'https://example.com/tochigi.jpg',
    },
    {
      id: '21',
      storeName: '立川店',
      address: '東京都立川市柴崎町2-10-1',
      closedDays: '月曜日',
      imageUrl: 'https://example.com/tochigi.jpg',
    }
]

export default storeData;